httpd:
  build: ./images/httpd/
  links:
   - idp:idp
   - ldap:ldap
   - sp:sp
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - ./vols/httpd/certificates:/etc/httpd/ssl/:ro

idp:
  build: ./images/shibboleth-idp/
  environment:
   - JETTY_MAX_HEAP=128m
  ports:
   - "8443:8443"
  volumes:
   - ./vols/shibboleth-idp/credentials:/opt/shibboleth-idp/credentials/:ro
   - ./vols/shibboleth-idp/ext-conf:/opt/shibboleth-idp/ext-conf/:ro
  links:
   - ldap:ldap

ldap:
  build: ./images/389ds/

sp:
  build: ./images/httpd-sp/ 
