httpd:
  build: ./httpd/
  links:
   - idp:idp
   - openldap:ldap
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - ./certificates:/etc/httpd/ssl:ro

idp:
  #build: ./shibboleth-idp/
  environment:
   - JETTY_MAX_HEAP=128m
  expose: 
   - "80"
   - "443"
  image: jtgasper3/shibboleth-idp:latest
  ports:
   - "8443:8443"
  #volumes:
  # - .:/code
  links:
   - openldap:ldap

openldap:
  #build: ./openldap/
  expose: 
   - "389"
  image: jtgasper3/openldap-basic
